### ISSUE TITLE
Segmentation when using surface proxy points for HSS example

### ISSUE THREAD

**Issue by f-t-s** [scalable-matrix/H2Pack#13]
I tried activating the surface proxy point method in the HSS example by changing `if (1)` -> `if (0)` in line 69 of `example_HSS.c`. 
However, when running the example, I get a segfault. I got similar results when using the exponential kernel, which should behave very similar to "kernels arising from potential theory" so I wanted to ask if there is anything else I need to change to try the proxy points.

**Comment by huanghua1994** [comment]
Hi Florian, it's a small bug in the `example_HSS.c`, I just fixed it in commit b793d74, please try the new code. Thank you for reporting the bug!

**Comment by f-t-s** [comment]
Seems to work now, thanks!
