### ISSUE TITLE
macOS installation

### ISSUE THREAD

**Issue by parshakova** [scalable-matrix/H2Pack#17]
what flags should I change to install H2Pack on macOS?
I set
`CC           = /usr/local/opt/llvm/bin/clang`
`OPENBLAS_INSTALL_DIR = /usr/local/opt/openblas/lib`
and installed Openblas and Openmp with `brew`, but get the following error

`$ make -f GCC-OpenBLAS.make
/usr/local/opt/llvm/bin/clang  -I/usr/local/opt/openblas/lib/include -Wall -g -std=gnu11 -O3 -fPIC  -DUSE_OPENBLAS -c H2Pack_HSS_ULV.c -o H2Pack_HSS_ULV.c.o
In file included from H2Pack_HSS_ULV.c:9:
In file included from ./H2Pack_config.h:100:
./linalg_lib_wrapper.h:16:10: fatal error: 'cblas.h' file not found
#include <cblas.h>
         ^~~~~~~~~
1 error generated.
make: *** [H2Pack_HSS_ULV.c.o] Error 1`

**Comment by huanghua1994** [comment]
I do not have the experience of using macOS, I will try my best guess. Since your OpenBLAS is installed with brew, your OpenBLAS should be installed at `/usr/local/opt/openblas`. You can check if directory `/usr/local/opt/openblas/include` has `cblas.h`. If it has this header file, you can set `OPENBLAS_INSTALL_DIR=/usr/local/opt/openblas`.

**Comment by parshakova** [comment]
Thank you very much, it fixed the openblas error!

Do you know if I should change any other flags to make it compile on macOS?
I modified CFLAGS in common.make to
`CFLAGS  = $(INCS) -Wall -g -std=gnu11 -O3 -fPIC $(DEFS) -target x86_64-apple-darwin -mmacosx-version-min=10.9`

I get the following error
`ar libH2Pack.a DAG_task_queue.c.o H2Pack_HSS_ULV.c.o H2Pack_ID_compress.c.o H2Pack_SPDHSS_H2.c.o H2Pack_aux_structs.c.o H2Pack_build.c.o H2Pack_build_periodic.c.o H2Pack_build_with_sample_point.c.o H2Pack_file_IO.c.o H2Pack_gen_proxy_point.c.o H2Pack_matmul.c.o H2Pack_matmul_periodic.c.o H2Pack_matvec.c.o H2Pack_matvec_periodic.c.o H2Pack_partition.c.o H2Pack_partition_periodic.c.o H2Pack_typedef.c.o H2Pack_utils.c.o utils.c.o
/Library/Developer/CommandLineTools/usr/bin/ar: illegal option -- H
usage:  ar -d [-TLsv] archive file ...
	ar -m [-TLsv] archive file ...
	ar -m [-abiTLsv] position archive file ...
	ar -p [-TLsv] archive [file ...]
	ar -q [-cTLsv] archive file ...
	ar -r [-cuTLsv] archive file ...
	ar -r [-abciuTLsv] position archive file ...
	ar -t [-TLsv] archive [file ...]
	ar -x [-ouTLsv] archive [file ...]
make: *** [libH2Pack.a] Error 1`

**Comment by xinxing02** [comment]
I used to get the same error in MacOS but I didn't know the error source. However, it turns out that this command line is not needed in all my usage. (@huanghua1994  might be able to explain what this generated .so file is used for.) All you need to do is to comment out the corresponding lines in common.make, i.e., 
```
  30     #cp $(LIB_SO) ../lib/$(LIB_SO)
  37 #$(LIB_SO): $(C_OBJS)
  38     #$(CC) -shared -o $@ $^
```

**Comment by parshakova** [comment]
I still get the same error...

Also do  you use this file [https://github.com/scalable-matrix/H2Pack/blob/master/src/common.make](https://github.com/scalable-matrix/H2Pack/blob/master/src/common.make) ?
The line count is different in this link than the one you provide

**Comment by huanghua1994** [comment]
@parshakova You may try to add `AR = ar -rcs` or `AR = ar rcs` in [src/common.make](https://github.com/scalable-matrix/H2Pack/blob/master/src/common.make) after line 9. If it works, I can update this file.

**Comment by parshakova** [comment]
still have same error.

the following command outputs `0`
`/usr/local/opt/llvm/bin/clang --version 2>&1 | grep -c "gcc"`

My gcc version output is
`$ gcc --version`
`Apple clang version 14.0.3 (clang-1403.0.22.14.1)`
`Target: x86_64-apple-darwin22.4.0`
`Thread model: posix`
`InstalledDir: /Library/Developer/CommandLineTools/usr/bin`

**Comment by parshakova** [comment]
Still does not work... with error
```
$ make -f GCC-OpenBLAS.make
make: *** No rule to make target `libH2Pack.so', needed by `install'.  Stop.
```

my `common.make` is

```
LIB_A   = libH2Pack.a
LIB_SO  = libH2Pack.so

C_SRCS  = $(wildcard *.c)
C_OBJS  = $(C_SRCS:.c=.c.o)

DEFS    = 
INCS    = 
CFLAGS  = $(INCS) -Wall -g -std=gnu11 -O3 -fPIC $(DEFS) -target x86_64-apple-darwin -mmacosx-version-min=10.9 

#ifeq ($(shell $(CC) --version 2>&1 | grep -c "icc"), 1)
#AR      = xiar rcs
#CFLAGS += -qopenmp -xHost
#endif

ifeq ($(shell $(CC) --version 2>&1 | grep -c "gcc"), 1)
AR      = ar -rcs
CFLAGS +=  -fopenmp -march=native -Wno-unused-result -Wno-unused-function
endif

ifeq ($(strip $(USE_MKL)), 1)
DEFS   += -DUSE_MKL
CFLAGS += -mkl
endif

ifeq ($(strip $(USE_OPENBLAS)), 1)
OPENBLAS_INSTALL_DIR = /usr/local/opt/openblas
DEFS   += -DUSE_OPENBLAS
INCS   += -I$(OPENBLAS_INSTALL_DIR)/include
endif

# Delete the default old-fashion double-suffix rules
.SUFFIXES:

.SECONDARY: $(C_OBJS)

all: install

install: $(LIB_A) $(LIB_SO)
	mkdir -p ../lib
	mkdir -p ../include
	mkdir -p ../include/ASTER/include
	cp -u $(LIB_A)  ../lib/$(LIB_A)
	#cp -u $(LIB_SO) ../lib/$(LIB_SO)
	cp -u *.h ../include/
	cp -u ASTER/include/*.h ../include/ASTER/include

$(LIB_A): $(C_OBJS) 
	ar rcs $@ $^

#$(LIB_SO): $(C_OBJS) 
#	$(CC) -shared -o $@ $^

%.c.o: %.c
	$(CC) $(CFLAGS) -c $^ -o $@

clean:
	rm -f $(C_OBJS) $(LIB_A) $(LIB_SO)

```


and my `GCC-OpenBLAS.make` is
```
CC           = /usr/local/opt/llvm/bin/clang
USE_MKL      = 0
USE_OPENBLAS = 1

include common.make

# GCC 10 need to manually specify using SVE, -march=native is not enough
# On A64FX SVE vector bits = 512, on other SVE supported processors this value might be different
USE_AARCH64_SVE = 0
SVE_VECTOR_BITS = 512
ifeq ($(strip $(USE_AARCH64_SVE)), 1)
CFLAGS := $(subst -march=native, -march=armv8.2-a+sve -msve-vector-bits=$(SVE_VECTOR_BITS), $(CFLAGS))
endif
```

**Comment by xinxing02** [comment]
My mistake. I think the error I came across before is different from yours. I'm using a Mac with M1 chip and now having some trouble with conflicts between ARM and X86. Your latest error is due to the correction I recommended earlier, where you've commented out 
```
#cp $(LIB_SO) ../lib/$(LIB_SO)
#$(LIB_SO): $(C_OBJS) 
#	$(CC) -shared -o $@ $^
```
You can uncomment these three lines. Or, you can comment out the ```$(LIB_SO)``` in the following line
```
install: $(LIB_A) #$(LIB_SO)
```

**Comment by parshakova** [comment]
Thank you for fast responses. I uncommented the three lines you mentioned, and error message changed to
```
$ make -f GCC-OpenBLAS.make
/usr/local/opt/llvm/bin/clang -shared -o libH2Pack.so DAG_task_queue.c.o H2Pack_HSS_ULV.c.o H2Pack_ID_compress.c.o H2Pack_SPDHSS_H2.c.o H2Pack_aux_structs.c.o H2Pack_build.c.o H2Pack_build_periodic.c.o H2Pack_build_with_sample_point.c.o H2Pack_file_IO.c.o H2Pack_gen_proxy_point.c.o H2Pack_matmul.c.o H2Pack_matmul_periodic.c.o H2Pack_matvec.c.o H2Pack_matvec_periodic.c.o H2Pack_partition.c.o H2Pack_partition_periodic.c.o H2Pack_typedef.c.o H2Pack_utils.c.o utils.c.o
Undefined symbols for architecture x86_64:
  "_LAPACKE_dgeqpf", referenced from:
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
  "_LAPACKE_dgeqrf", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
  "_LAPACKE_dgetrf", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
  "_LAPACKE_dorgqr", referenced from:
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
  "_LAPACKE_dormqr", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_LU_solve in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_solve in H2Pack_HSS_ULV.c.o
  "_LAPACKE_dpotrf", referenced from:
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
  "_LAPACKE_dsyevd", referenced from:
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
  "_cblas_ddot", referenced from:
      _H2P_partial_pivot_QR in H2Pack_ID_compress.c.o
      _H2P_partial_pivot_QR_kdim in H2Pack_ID_compress.c.o
  "_cblas_dgemm", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
      _H2P_partial_pivot_QR_kdim in H2Pack_ID_compress.c.o
      _H2P_build_explicit_U in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_acc_matvec in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_calc_HSS_Bij in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
      ...
  "_cblas_dgemv", referenced from:
      _H2P_HSS_ULV_LU_solve in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_solve in H2Pack_HSS_ULV.c.o
      _H2P_partial_pivot_QR_kdim in H2Pack_ID_compress.c.o
      _H2P_matvec_fwd_transform in H2Pack_matvec.c.o
      _H2P_matvec_bwd_transform in H2Pack_matvec.c.o
      _H2P_matvec_dense_mult0_AOT_task_block in H2Pack_matvec.c.o
      _H2P_matvec_dense_mult_AOT in H2Pack_matvec.c.o
      ...
  "_cblas_dnrm2", referenced from:
      _H2P_partial_pivot_QR in H2Pack_ID_compress.c.o
      _H2P_partial_pivot_QR_kdim in H2Pack_ID_compress.c.o
      _H2P_dense_mat_normalize_columns in H2Pack_aux_structs.c.o
  "_cblas_dtrsm", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_LU_solve in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_solve in H2Pack_HSS_ULV.c.o
      _H2P_ID_compress in H2Pack_ID_compress.c.o
      _H2P_SPDHSS_H2_calc_HSS_Bij in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_build in H2Pack_SPDHSS_H2.c.o
      ...
  "_omp_get_max_threads", referenced from:
      _H2P_generate_proxy_point_nlayer in H2Pack_gen_proxy_point.c.o
      _H2P_init in H2Pack_typedef.c.o
  "_omp_get_num_threads", referenced from:
      _H2P_eval_kernel_matrix_OMP in H2Pack_utils.c.o
  "_omp_get_thread_num", referenced from:
      _H2P_HSS_ULV_LU_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_LU_solve in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_factorize in H2Pack_HSS_ULV.c.o
      _H2P_HSS_ULV_Cholesky_solve in H2Pack_HSS_ULV.c.o
      _H2P_build_explicit_U in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_acc_matvec in H2Pack_SPDHSS_H2.c.o
      _H2P_SPDHSS_H2_wrap_new_HSS in H2Pack_SPDHSS_H2.c.o
      ...
  "_openblas_set_num_threads", referenced from:
      _H2P_partial_pivot_QR in H2Pack_ID_compress.c.o
      _H2P_partial_pivot_QR_kdim in H2Pack_ID_compress.c.o
      _H2P_ID_compress in H2Pack_ID_compress.c.o
      _H2P_build_H2_UJ_proxy in H2Pack_build.c.o
      _H2P_build_HSS_UJ_hybrid in H2Pack_build.c.o
      _H2P_build_H2_UJ_sample in H2Pack_build_with_sample_point.c.o
ld: symbol(s) not found for architecture x86_64
clang-16: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [libH2Pack.so] Error
```

**Comment by xinxing02** [comment]
This is finally the error I had before and referred to before. This .so file is not needed to run examples and the python interface. You can now compile the examples and see whether it works. If you don't want to see this error message every time you compile, you can sweep the dust under the rug by adding the extra comment (plus the previous three) in 
```
install: $(LIB_A) #$(LIB_SO)
```

**Comment by parshakova** [comment]
I had to add this
```
install: $(LIB_A) #$(LIB_SO)
	mkdir -p ../lib
	mkdir -p ../include
	mkdir -p ../include/ASTER/include
	rsync -u $(LIB_A)  ../lib/$(LIB_A)
	#rsync -u $(LIB_SO) ../lib/$(LIB_SO)
	rsync -u *.h ../include/
	rsync -u ASTER/include/*.h ../include/ASTER/include
```
rsync instead of cp, and at the end of execution of ` CC=/usr/local/opt/llvm/bin/clang python setup.py install` the output was
```
Installed /opt/anaconda3/envs/routing/lib/python3.9/site-packages/pyh2pack-1.0.0-py3.9-macosx-10.9-x86_64.egg
Processing dependencies for pyh2pack==1.0.0
Finished processing dependencies for pyh2pack==1.0.0
```

I can import pyh2pack, but while running you basic python test, I get an error
```python
     [12]#  H2 matvec
     [13]  x = np.random.normal(size=(krnl_dim*N))
     [14] y = A.h2matvec(x)
     [16]#  direct matvec for a subset of rows
     [17]start_pt = 8000

AttributeError: 'pyh2pack.H2Mat' object has no attribute 'h2matvec'
```
does it mean the installation is not successful?

**Comment by xinxing02** [comment]
I guess that you might be using an old version of the example code. The example code (https://github.com/scalable-matrix/H2Pack/blob/master/pyh2pack/example.py) now uses A.matvec(x).

**Comment by parshakova** [comment]
Wow, it works now, thank you!!!

P.S.  I got  outdated example from here [https://github.com/scalable-matrix/H2Pack/wiki/Using-H2Pack-in-Python](https://github.com/scalable-matrix/H2Pack/wiki/Using-H2Pack-in-Python)

**Comment by parshakova** [comment]
Is it possible to use your package to represent in H^2 any arbitrary matrix?

**Comment by xinxing02** [comment]
> Wow, it works now, thank you!!!
> 
> P.S. I got outdated example from here https://github.com/scalable-matrix/H2Pack/wiki/Using-H2Pack-in-Python

Thanks for pointing it out! We will update the document, and also try to fix the .so issue in MacOS.

**Comment by xinxing02** [comment]
> Is it possible to use your package to represent in H^2 any given matrix?

This package only works for kernel matrices defined by translational invariant kernel function with 2D/3D points. For an arbitrary matrix without any analytic information, you will need to resort to algebraic compression methods such as QR, ACA, or randomized methods to construct H2 matrix representation. In general, these methods can lead to significantly more computational cost. Furthermore, the proper partitioning of the given matrix into subblocks always requires some additional information about the matrix.

**Comment by parshakova** [comment]
@xinxing02 could you please let me know if is there a way to get the true kernel matrix that is being compressed?
I would like to use it for comparison of your method

**Comment by xinxing02** [comment]
You can refer to line 98 in https://github.com/scalable-matrix/H2Pack/blob/master/pyh2pack/example.py as an example to evaluate the wanted matrix blocks.

**Comment by parshakova** [comment]
is there  a command to get the dense representation of the data-sparse matrix?
It can be retrieved column by column using matvec operations with $e_i$ vectors, I am wondering if there is a method for it

**Comment by huanghua1994** [comment]
Currently, there is no such function that can generate the dense representation of the H2 matrix. 
If `n` is very large, `A.matmul(np.eye(n))` requires a lot of memory. You should use multiple matmuls instead of one large matmul.

Outputs like
`H2 representation U, B, D     : 156.91, 2089.83, 3660.22 (MB)`
are the exact memory usage in H2Pack. The memory usage of some small arrays used in H2 matrix is not printed in the output. Currently, all floating points are in double precision.

**Comment by parshakova** [comment]
`n=1000` is it considered big?
could you please let me know how can I restrict matvec to small submatrix?

**Comment by huanghua1994** [comment]
`n=1000` is considered small for an H2 matrix.  I would suggest that you try a larger `n`, but do not use one large matmul.

Can you explain the meaning of "restrict matvec to small submatrix"? If you only want to use a submatrix of the H2 representation, for example, you only want to compute `A(1:100, 1:100) * x` with `n >= 100`, H2Pack does not support such an operation.

**Comment by huanghua1994** [comment]
One solution of "restrict matvec to small submatrix" is that you construct an input vector with some zeros in it. For example, `n=10000`, and you only want `A(101:200, 201:300) * x`, then you can construct an input vector `b = [zeros(200, 1); x; zeros(99700, 1)]`, compute `c = A * b`.

**Comment by parshakova** [comment]
thank you very much for you answers

do you have recommendations on how can I materialize the full H2 matrix in dense format?
I want a full matrix to run different comparison with the true kernel  matrix.
If I  extract column by column using matvec operation
```python
A_H2 = np.zeros((n, n))
Id = np.eye(n)
for i in range(n):
    A_H2[:,i] = A_H2Mat.matvec(Id[:,i])
```
I get this message for every matvec operation
`** On entry to DGEMV  parameter number  6 had an illegal value`

**Comment by huanghua1994** [comment]
1. `n=1000` is too small for an H2 matrix. It is possible that the hierarchical partitioning in the H2 matrix not working correctly. You can try using a larger `n` value.
2. Can you run the basic matvec example? If that works, I suggest that you modify and reuse the input vector like this (I haven't tried this Python code myself, it may have syntax errors, but you can get my point):
```python
for i in range(n):
    x = np.zeros(n)
    x[i] = 1.0
    A_H2[:, i] = A_H2Mat.matvec(x)
```
If I have some time later this week I can look into the error message you have. 
3. The discussion is no longer related to macOS installation. I will close this issue. Please email me for further questions.
